Expose command line option to configure umask for directories and files
restic/rest-server pull request #190
Opened 2022-04-14 17:50 UTC by mlusetti

What is the purpose of this change? What does it change?
--------------------------------------------------------
This will fix #189 

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
I proposed in #189 

Checklist
---------

- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/rest-server/commits/master)
- [X] I'm done, this Pull Request is ready for review

2022-04-15 07:24 UTC, mlusetti commented
The test/lint check fail on code I haven't touched, so I guess is failing the same way in the master branch too

2022-04-15 07:42 UTC, fd0 commented
I've fixed this in master (sorry about that) and also raised the min Go version to 1.15. Unfortunately you haven't enabled maintainer edits, so I'm unable to push the fixed commits. Can you please enable that? Thanks!

2022-04-15 07:59 UTC, mlusetti commented
> I've fixed this in master (sorry about that) and also raised the min Go version to 1.15. Unfortunately you haven't enabled maintainer edits, so I'm unable to push the fixed commits. Can you please enable that? Thanks!

I've checked "Allow edits by maintainers" flag ... Should I do anything more ?

2022-04-15 08:24 UTC, fd0 commented
Hm, no, that's exactly the setting. Maybe I did something wrong? I'll have a look

2022-04-15 08:28 UTC, fd0 commented
Sigh, PEBKAC, I tried to push to your "restic" repo, instead of the "rest-server" repo. :grin:

2022-04-15 09:44 UTC, mlusetti commented
In my env it didn't fail to build on Go 1.15 and io/fs is not present in the source code

2022-04-15 09:52 UTC, mlusetti commented
I reworked your diff cause it has lost (a rebase?) my last commit

2022-04-19 07:31 UTC, mlusetti commented
Hi @fd0 do you think there's need for other changes in the diff ?

2022-04-20 20:12 UTC, MichaelEischer commented
@mlusetti I think fd0 intentionally removed the "make it go 1.14 buildable" commit as it is no longer necessary after rebasing to the current master branch.

2022-04-21 06:56 UTC, mlusetti commented
> @mlusetti I think fd0 intentionally removed the "make it go 1.14 buildable" commit as it is no longer necessary after rebasing to the current master branch.

Thanks for your pointer but as far as I can see io/fs package is not in GOROOT in 1.15 too ... Am I missing something ?

2022-10-10 14:12 UTC, ianneub commented
Is there anything that I could help with to get this PR merged? I could use this patch for a situation very similar to @mlusetti . I am trying to backup the restic files from a user that is different than the rest-server's user. Being able to set new file permissions to `660` for new files would allow this to work in my situation.

Thanks so much for everyone's efforts thus far on this patch and Restic in general!

2022-10-25 16:46 UTC, mlusetti commented
Any news on this one ?

To me is a simple diff which don't introduce backward incompatibilities nor change any default behaviors.

Thanks

2022-10-25 19:43 UTC, rawtaz commented
I'm so stupid. I [asked](https://github.com/restic/rest-server/issues/189#issuecomment-1213486442) over two months ago in #189 what the more specific use case was, which @mlusetti kindly [answered](https://github.com/restic/rest-server/issues/189#issuecomment-1216427399). @MichaelEischer also commented. But I looked for an answer here in this PR.

So, the use case is to be able to let groups read the repository files. This is pretty much in line with a similar change introduced in restic here: https://github.com/restic/restic/pull/3419/files - it allows for group access to the repository files.

Generally speaking our preference would be to have the same behavior here in rest-server to what we have there in restic, or at least restrict the options to the current default and group-readable. We feel the PR as it is now is too allowing basically, we'd like to meet the specific use case instead of opening up to potential mishaps, at least for now.

2023-09-05 17:38 UTC, MichaelEischer requested changes
Please replace the options with a `--group-accessible-repositories` (maybe someone can come up with a better name). So far it looks like that option should cover the reported use cases and is not prone to accidental misuse as the current options.

2023-09-11 19:56 UTC, MichaelEischer reviewed
I'd prefer to grant the users groups both read and write access. By setting a corresponding umask it should still be possible to prevent those groups from actually being able to write to the repository storage.

regarding the option name @rawtaz suggested a few possible variants like: `--group-access`, `--group-accessible`, `--group-accessible-repos` or `--group-repos`. I'd also throw in an additional `--group-accessible-data`. What do you think?

2023-09-11 19:56 UTC, MichaelEischer commented on repo/repo.go
> +	// if opt.dirMode == 0 {
I don't think we need these comments.

2023-09-11 19:56 UTC, MichaelEischer commented on repo/repo.go
> +const GroupReadableDirMode os.FileMode = 0750
I'd prefer `0770` and `0660` an leave further restrictions to the umask used to run `rest-server`.

2023-09-11 19:56 UTC, MichaelEischer commented on repo/repo.go
> +  // If set, we will panic when an internal server error happens. This
That comment doesn't look like it belongs here.

2024-03-29 09:59 UTC, eloo commented
Hi there,

was the current state of this PR?
I'm right running in the same issue as i want to backup my PVC using VolSync to the restic-rest-server but the file permissions making it tricky to access the backup afterwards from my local machine. 

I guess this PR would fix this because i can now use my shared group permissions to access the files.

Thanks

2024-03-29 16:53 UTC, MichaelEischer commented
@mlusetti Are you still interested in finishing this PR? Or does someone else want to take over?

2024-04-04 17:59 UTC, MichaelEischer commented
> I can try to see if I've some spare cycle, no guarantees. If anyone faster that would be nice too.

Just open a new PR once you're ready and refer to this one. Then I'll close the old one.

2024-11-02 10:21 UTC, mlusetti commented
Added #308 as requested

2025-02-17 21:18 UTC, closed without merging