feat: allow logging to stdout, stderr
restic/rest-server pull request #217
Opened 2023-03-23 18:59 UTC by HeikoSchlittermann

What is the purpose of this change? What does it change?
--------------------------------------------------------

The --log option accepts "stdout", "stderr" as filenames. This prevents rest-server from opending these files, it simply writs the the STDOUT or STDERR stream provided by the caller.

**BREAKING** in case use really used "stdout", "stderr" to specify file names, you'll need to update your rest-server invocation to use "./stdout", "./stderr".

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

No.

Checklist
---------

- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
      Not in the manual, but in the options help
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/rest-server/commits/master)
- [ ] I'm done, this Pull Request is ready for review

2023-04-08 18:49 UTC, MichaelEischer commented
What is the use case for logging to stderr? For stdout a pretty common name would be "-", that is `--log -`.

2023-04-11 22:58 UTC, HeikoSchlittermann commented
I currently to not have a use case for logging to STDERR. I suggested it for both (stderr, stdout) just for completeness. Logging to STDOUT though I have a use case for: I'd like to have Systemd capture all the output. Depending on the invocation, `rest-server` can't (re)open STDOUT (permissions).

I'm fine with `--log -` too. But IMHO `--log stdout` is more self-explanatory. (Using `--log /dev/sdout` with built-in magic would assume, that `/dev/stdout` is identical to the STDOUT provided by the caller.)

2023-04-22 09:39 UTC, MichaelEischer requested changes
> I'm fine with `--log -` too. But IMHO `--log stdout` is more self-explanatory.

Both variants are special cases that can be pretty surprising. Although using `-` to mean stdout/stdin is quite common for unix commands. Thus, we should stick to that convention. Please change the PR to use `--log -` to log to stdout and remove the stderr variant.

2023-04-30 12:53 UTC, MichaelEischer approved these changes
LGTM. I've tweaked the changelog to be less technical.

2023-04-30 12:56 UTC, merged