Hardened tls cipher suits and added option for tls min version
restic/rest-server pull request #315
Opened 2024-12-05 12:16 UTC by DarkSpir

What is the purpose of this change? What does it change?
--------------------------------------------------------

With tls activated, the rest-server will provide insecure tls versions and insecure or broken tls cipher suits. This change configures the default settings in tls mode, sets a secure set of cipher suits (according to CIS NGINX Benchmark v2.1.0) and sets up TLSv1.2 as min version. It also adds a command line parameter to select a different version as min version.

The current version of the crypto.tls library also sets a small, secure set of cipher suits as default and limits the available TLS versions to 1.2 and 1.3. Earlier versions are also available but have to be explicitly enabled during compilation.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes #251 

Checklist
---------

- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/rest-server/commits/master)
- [ ] I'm done, this Pull Request is ready for review

2024-12-05 13:09 UTC, DarkSpir commented
I actually have no idea how the tests work. From what I can guess out of main_test.go I assume it tests the program response to certain conditions to ensure it will throw errors when parameters are missing or misleading. If that's the case I think it is not necessary to add tests for what I did, because if `--tls-min-ver` is missing or provides a wrong value, it defaults to TLSv1.2. Even when a user sets --tls-min-ver 1.0 and the build option is not set, the library will internally default to 1.2.

2025-02-07 22:07 UTC, MichaelEischer requested changes
https://github.com/restic/rest-server/pull/322 will bump Go to 1.22 which disables TLS before 1.2 by default. TLS 1.2 is older than Go 1.0. So I don't think anyone will ever need an older TLS version (if they do then they should fix their setup instead).

That would sort of make the `--tls-min-version` somewhat obsolete. WDYT?

Removing the 3DES ciphers is fine. The cipher suite subset is already added by https://datatracker.ietf.org/doc/html/rfc5289 which is from 2008. That also implicitly means that clients that only support TLS < 1.2 won't be able to use any of those ciphers, which is one reason more to not even consider offering TLS 1.0 and 1.1.

2025-02-07 22:13 UTC, MichaelEischer commented on cmd/rest-server/main.go
> +		CurvePreferences: []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
I'd prefer to stick to the Go default here.

2025-02-08 10:48 UTC, DarkSpir commented on README.md
> +      --tls-min-ver string     TLS min version (default: 1.2) (default "1.2")
Good eye, I will change that. Thanks.

2025-02-08 10:50 UTC, DarkSpir commented on cmd/rest-server/main.go
> +		tlscfg.MinVersion = tls.VersionTLS12
Personally I'm a big fan of "mitigatable errors should be mitigated" but this is your show. I'll change the default branch.

2025-02-08 11:02 UTC, DarkSpir commented on cmd/rest-server/main.go
> +	case "1.0":
On a security level, I agree. And since people would have to go the extra mile and compile the source with GODEBUG="tls10server=1" set to enable it... I'm not even sure why I put that in there. I'll take it out.

2025-02-08 11:05 UTC, DarkSpir commented on cmd/rest-server/main.go
> +		CurvePreferences: []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
At this point I can't remember. I know I followed the CIS hardening recommendations for nginx web servers TLS settings but it is possible that this was more a personal preference of mine. I'm totally fine with the Go 1.23 defaults and it makes sense to keep them. I changed that.

2025-02-08 11:09 UTC, DarkSpir commented
> That would sort of make the `--tls-min-version` somewhat obsolete. WDYT?

Technically yes but it could still be used to enforce a TLS 1.3 only-setup which could be preferable to calm down a few paranoid CISOs out there. Should we remove it entirely or keep and document it?

2025-02-17 20:57 UTC, MichaelEischer commented
> Should we remove it entirely or keep and document it?

We can keep the flag. But we should document the allowed TLS versions.

2025-02-17 20:57 UTC, MichaelEischer commented on cmd/rest-server/main.go
> +	flags.StringVar(&rv.Server.TLSMinVer, "tls-min-ver", rv.Server.TLSMinVer, "TLS min version (default: 1.2)")
This still results in `(default: 1.2) (default: 1.2)` in the help text as cobra automatically appends the default value. Ideally this should also include the allowed values: `one of (1.2|1.3)`

2025-02-17 20:57 UTC, MichaelEischer commented on README.md
> +By default the server uses HTTP protocol.  This is not very secure since with Basic Authentication, user name and passwords will be sent in clear text in every request.  In order to enable TLS suppor
Please document the supported values.

2025-02-17 20:57 UTC, MichaelEischer commented on cmd/rest-server/main.go
> +		return fmt.Errorf("Unsupported TLS min version: %s", app.Server.TLSMinVer)
The error should report the allowed version numbers.

2025-03-27 14:26 UTC, leapfog commented
Is there a chance of a new release, with sane SSL defaults, in the near future?

2025-03-28 13:12 UTC, DarkSpir commented on cmd/rest-server/main.go
> +	flags.StringVar(&rv.Server.TLSMinVer, "tls-min-ver", rv.Server.TLSMinVer, "TLS min version (default: 1.2)")
Ah, I didn't know that but I changed it and the test builds output looked okay. I'm not 100% sure with the text thou.

2025-03-28 13:12 UTC, DarkSpir commented on README.md
> +By default the server uses HTTP protocol.  This is not very secure since with Basic Authentication, user name and passwords will be sent in clear text in every request.  In order to enable TLS suppor
I added the values.

2025-03-28 13:28 UTC, DarkSpir commented
Sorry, I somehow forgot about this. I changed everything as requested and I hope we're good to go now.

2025-04-14 19:08 UTC, MichaelEischer approved these changes
Rebased again due to another conflict and fixed the linter error.

2025-04-14 19:09 UTC, merged

2025-04-14 21:01 UTC, Framsfex commented
https://github.com/restic/rest-server/releases/ offers still rest-server 0.13.0 (2024-07-26)